"""Add cash_sessions, payments, Invoice.cash_session_id

Revision ID: 000416c66861
Revises: 54fffbb20899
Create Date: 2026-08-26 17:07:47.173484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000416c66861'
down_revision: Union[str, None] = '54fffbb20899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_amount_expected', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_amount_counted', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', name='cashsessionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_activity_id'), 'cash_sessions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_company_id'), 'cash_sessions', ['company_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('NUMERARIO', 'MULTICAIXA', 'MULTICAIXA_EXPRESS', 'TRANSFERENCIA', 'OUTRO', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('cash_session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_cash_session_id'), 'invoices', ['cash_session_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'cash_sessions', ['cash_session_id'], ['id'])
    op.alter_column('recipe_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_cash_session_id'), table_name='invoices')
    op.drop_column('invoices', 'cash_session_id')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cash_sessions_company_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_activity_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    # ### end Alembic commands ###
