"""add cash_movement_reasons and cash_movements tables

Revision ID: 05ccc3fa9605
Revises: d36eddc984ff
Create Date: 2026-09-08 10:34:30.710794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ccc3fa9605'
down_revision: Union[str, None] = 'd36eddc984ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Raw SQL for this table only: 'direction' reuses the 'movementdirection' Postgres
    # enum type already created by an earlier migration (movement_types table). Alembic's
    # op.create_table() forces checkfirst=False on embedded Enum columns, which ignores
    # create_type=False and always attempts CREATE TYPE - a known SQLAlchemy 2.0 gotcha.
    # Raw SQL sidesteps that DDL machinery entirely and just references the existing type.
    op.execute('''
        CREATE TABLE cash_movement_reasons (
            id uuid NOT NULL,
            company_id uuid NOT NULL,
            name varchar(100) NOT NULL,
            direction movementdirection NOT NULL,
            is_active boolean NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (id),
            FOREIGN KEY(company_id) REFERENCES companies (id)
        )
    ''')
    op.create_index(op.f('ix_cash_movement_reasons_company_id'), 'cash_movement_reasons', ['company_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('TRANSFERENCIA', 'ENTRADA_EXTERNA', 'SAIDA_EXTERNA', name='cashmovementtype'), nullable=False),
    sa.Column('source_pos_id', sa.UUID(), nullable=True),
    sa.Column('source_cash_office_id', sa.UUID(), nullable=True),
    sa.Column('destination_pos_id', sa.UUID(), nullable=True),
    sa.Column('destination_cash_office_id', sa.UUID(), nullable=True),
    sa.Column('reason_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (destination_pos_id IS NOT NULL AND destination_cash_office_id IS NOT NULL)', name='ck_cash_movement_single_destination'),
    sa.CheckConstraint('NOT (source_pos_id IS NOT NULL AND source_cash_office_id IS NOT NULL)', name='ck_cash_movement_single_source'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_cash_office_id'], ['cash_offices.id'], ),
    sa.ForeignKeyConstraint(['destination_pos_id'], ['points_of_sale.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['cash_movement_reasons.id'], ),
    sa.ForeignKeyConstraint(['source_cash_office_id'], ['cash_offices.id'], ),
    sa.ForeignKeyConstraint(['source_pos_id'], ['points_of_sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_company_id'), 'cash_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_destination_cash_office_id'), 'cash_movements', ['destination_cash_office_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_destination_pos_id'), 'cash_movements', ['destination_pos_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_movement_date'), 'cash_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_cash_movements_reason_id'), 'cash_movements', ['reason_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_source_cash_office_id'), 'cash_movements', ['source_cash_office_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_source_pos_id'), 'cash_movements', ['source_pos_id'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here,
    # same as in prior migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_movements_source_pos_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_source_cash_office_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_reason_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_movement_date'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_destination_pos_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_destination_cash_office_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_company_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_movement_reasons_company_id'), table_name='cash_movement_reasons')
    op.drop_table('cash_movement_reasons')
    # ### end Alembic commands ###
