"""Add exemption_reason_id to Product and Service

Revision ID: 06dc09bfe96f
Revises: 8ee052c8239c
Create Date: 2026-08-29 23:27:01.657255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dc09bfe96f'
down_revision: Union[str, None] = '8ee052c8239c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('exemption_reason_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'vat_codes', ['exemption_reason_id'], ['id'])
    op.add_column('services', sa.Column('exemption_reason_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'services', 'vat_codes', ['exemption_reason_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'exemption_reason_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'exemption_reason_id')
    # ### end Alembic commands ###
