"""add generic open account (running tab) system

Revision ID: 0a0aebfd4dd0
Revises: 83c885b9011d
Create Date: 2026-09-13 09:20:24.618856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0aebfd4dd0'
down_revision: Union[str, None] = '83c885b9011d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('pos_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'FECHADA', name='openaccountstatus'), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['points_of_sale.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_accounts_activity_id'), 'open_accounts', ['activity_id'], unique=False)
    op.create_index(op.f('ix_open_accounts_company_id'), 'open_accounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_open_accounts_pos_id'), 'open_accounts', ['pos_id'], unique=False)
    op.create_index(op.f('ix_open_accounts_resource_id'), 'open_accounts', ['resource_id'], unique=False)
    op.create_table('open_account_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['open_accounts.id'], ),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_account_lines_account_id'), 'open_account_lines', ['account_id'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.


def downgrade() -> None:
    op.drop_index(op.f('ix_open_account_lines_account_id'), table_name='open_account_lines')
    op.drop_table('open_account_lines')
    op.drop_index(op.f('ix_open_accounts_resource_id'), table_name='open_accounts')
    op.drop_index(op.f('ix_open_accounts_pos_id'), table_name='open_accounts')
    op.drop_index(op.f('ix_open_accounts_company_id'), table_name='open_accounts')
    op.drop_index(op.f('ix_open_accounts_activity_id'), table_name='open_accounts')
    op.drop_table('open_accounts')
    # ### end Alembic commands ###
