"""add suppliers table and link to stock movement documents

Revision ID: 1385b79792a3
Revises: 176db455cb38
Create Date: 2026-09-18 23:40:36.818197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1385b79792a3'
down_revision: Union[str, None] = '176db455cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_supplier_company_name')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.
    op.add_column('stock_movement_documents', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_movement_documents_supplier_id'), 'stock_movement_documents', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'stock_movement_documents', 'suppliers', ['supplier_id'], ['id'])


def downgrade() -> None:
    op.drop_constraint(None, 'stock_movement_documents', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movement_documents_supplier_id'), table_name='stock_movement_documents')
    op.drop_column('stock_movement_documents', 'supplier_id')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
