"""Add fiscal_years and fiscal_periods tables

Revision ID: 169475be90b7
Revises: 24537a741945
Create Date: 2026-08-21 09:34:21.681284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169475be90b7'
down_revision: Union[str, None] = '24537a741945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_fiscal_year_company_year')
    )
    op.create_index(op.f('ix_fiscal_years_company_id'), 'fiscal_years', ['company_id'], unique=False)
    op.create_table('fiscal_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'month', name='uq_fiscal_period_year_month')
    )
    op.create_index(op.f('ix_fiscal_periods_company_id'), 'fiscal_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_periods_fiscal_year_id'), 'fiscal_periods', ['fiscal_year_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fiscal_periods_fiscal_year_id'), table_name='fiscal_periods')
    op.drop_index(op.f('ix_fiscal_periods_company_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_fiscal_years_company_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    # ### end Alembic commands ###
