"""Add fiscal_regimes table and Company.fiscal_regime_id

Revision ID: 1b703146ed84
Revises: 358779571576
Create Date: 2026-08-24 17:50:38.538635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b703146ed84'
down_revision: Union[str, None] = '358779571576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_regimes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('allows_nor', sa.Boolean(), nullable=False),
    sa.Column('allows_red', sa.Boolean(), nullable=False),
    sa.Column('allows_ise', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('companies', sa.Column('fiscal_regime_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'fiscal_regimes', ['fiscal_regime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'fiscal_regime_id')
    op.drop_table('fiscal_regimes')
    # ### end Alembic commands ###
