"""Add code to Establishment

Revision ID: 1da70b541e9f
Revises: 9700d1896998
Create Date: 2026-08-30 09:06:42.800501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da70b541e9f'
down_revision: Union[str, None] = '9700d1896998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('code', sa.String(length=20), nullable=False))
    op.create_unique_constraint('uq_establishment_company_code', 'establishments', ['company_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_establishment_company_code', 'establishments', type_='unique')
    op.drop_column('establishments', 'code')
    # ### end Alembic commands ###
