"""Enrich Customer (2-tab fields), add CustomerBankAccountLink, Country.default_currency_id

Revision ID: 1dc0c2365d66
Revises: 96b141597813
Create Date: 2026-08-29 11:44:03.782571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc0c2365d66'
down_revision: Union[str, None] = '96b141597813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE customerstatus AS ENUM ('ACTIVO', 'APROVADO', 'BLOQUEADO', 'ELIMINADO', 'INACTIVO', 'NAO_APROVADO', 'POR_ACTIVAR', 'POR_AVALIAR', 'SUSPENSO')")
    op.create_table('customer_bank_account_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('company_bank_account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_bank_account_id'], ['company_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'company_bank_account_id', name='uq_customer_bank_account_link')
    )
    op.create_index(op.f('ix_customer_bank_account_links_customer_id'), 'customer_bank_account_links', ['customer_id'], unique=False)
    op.add_column('countries', sa.Column('default_currency_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'countries', 'currencies', ['default_currency_id'], ['id'])
    op.add_column('customers', sa.Column('customer_code', sa.String(length=30), nullable=True))
    op.execute("ALTER TABLE customers ADD COLUMN legal_person_type legalpersontype NOT NULL DEFAULT 'JURIDICA'")
    op.add_column('customers', sa.Column('is_final_consumer', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('customers', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('customers', sa.Column('registration_date', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    op.add_column('customers', sa.Column('fiscal_name', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('currency_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('country_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('payment_term_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('payment_method_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('withholding_tax_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('status', sa.Enum('ACTIVO', 'APROVADO', 'BLOQUEADO', 'ELIMINADO', 'INACTIVO', 'NAO_APROVADO', 'POR_ACTIVAR', 'POR_AVALIAR', 'SUSPENSO', name='customerstatus', create_type=False), nullable=False, server_default='ACTIVO'))
    op.create_foreign_key(None, 'customers', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'withholding_taxes', ['withholding_tax_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'currencies', ['currency_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'payment_method_catalog', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'payment_terms', ['payment_term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'withholding_tax_id')
    op.drop_column('customers', 'payment_method_id')
    op.drop_column('customers', 'payment_term_id')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'province_id')
    op.drop_column('customers', 'country_id')
    op.drop_column('customers', 'currency_id')
    op.drop_column('customers', 'fiscal_name')
    op.drop_column('customers', 'registration_date')
    op.drop_column('customers', 'description')
    op.drop_column('customers', 'is_final_consumer')
    op.execute("ALTER TABLE customers DROP COLUMN legal_person_type")
    op.drop_column('customers', 'customer_code')
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.drop_column('countries', 'default_currency_id')
    op.drop_index(op.f('ix_customer_bank_account_links_customer_id'), table_name='customer_bank_account_links')
    op.drop_table('customer_bank_account_links')
    op.execute("DROP TYPE customerstatus")
    # ### end Alembic commands ###
