"""Add service_id to InvoiceLine, make product_id nullable

Revision ID: 22c27c1abe44
Revises: e405dd6833bf
Create Date: 2026-09-01 16:31:28.272166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c27c1abe44'
down_revision: Union[str, None] = 'e405dd6833bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('service_id', sa.UUID(), nullable=True))
    op.alter_column('invoice_lines', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'invoice_lines', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_lines', type_='foreignkey')
    op.alter_column('invoice_lines', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invoice_lines', 'service_id')
    # ### end Alembic commands ###
