"""Add document_reference to Invoice

Revision ID: 3881aa6284a5
Revises: 22c27c1abe44
Create Date: 2026-09-01 17:53:17.643848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3881aa6284a5'
down_revision: Union[str, None] = '22c27c1abe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('document_reference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'document_reference')
    # ### end Alembic commands ###
