"""Add converted_to_invoice_id to Invoice

Revision ID: 41d3d7c03137
Revises: 1b15f12af837
Create Date: 2026-09-03 00:35:42.316162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d3d7c03137'
down_revision: Union[str, None] = '1b15f12af837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('converted_to_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'invoices', ['converted_to_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'converted_to_invoice_id')
    # ### end Alembic commands ###
