"""Add area toggles to DocumentSeries

Revision ID: 4bfbdf0bce8d
Revises: 4ddbd2688ad8
Create Date: 2026-09-01 12:24:48.388985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfbdf0bce8d'
down_revision: Union[str, None] = '4ddbd2688ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_series', sa.Column('is_facturacao', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('document_series', sa.Column('is_tesouraria', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('document_series', sa.Column('is_compras', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_series', 'is_compras')
    op.drop_column('document_series', 'is_tesouraria')
    op.drop_column('document_series', 'is_facturacao')
    # ### end Alembic commands ###
