"""Add electronic_eligible to DocumentType

Revision ID: 4ddbd2688ad8
Revises: cbbc7d12504a
Create Date: 2026-09-01 12:18:25.499910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddbd2688ad8'
down_revision: Union[str, None] = 'cbbc7d12504a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('electronic_eligible', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'electronic_eligible')
    # ### end Alembic commands ###
