"""Add document_type_id to Invoice, fix uniqueness constraint

Revision ID: 4e5343cdb49b
Revises: 1da70b541e9f
Create Date: 2026-08-30 09:20:19.970255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5343cdb49b'
down_revision: Union[str, None] = '1da70b541e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('document_type_id', sa.UUID(), nullable=True))
    op.alter_column('invoices', 'series',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint('uq_invoice_company_series_number', 'invoices', type_='unique')
    op.create_unique_constraint('uq_invoice_company_doctype_series_number', 'invoices', ['company_id', 'document_type_id', 'series', 'number'])
    op.create_foreign_key(None, 'invoices', 'document_types', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint('uq_invoice_company_doctype_series_number', 'invoices', type_='unique')
    op.create_unique_constraint('uq_invoice_company_series_number', 'invoices', ['company_id', 'series', 'number'])
    op.alter_column('invoices', 'series',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('invoices', 'document_type_id')
    # ### end Alembic commands ###
