"""Add retention_total to Invoice

Revision ID: 4f8e7fd5ac3e
Revises: 3881aa6284a5
Create Date: 2026-09-02 09:35:37.080032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8e7fd5ac3e'
down_revision: Union[str, None] = '3881aa6284a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('retention_total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'retention_total')
    # ### end Alembic commands ###
