"""Add MovementSeries

Revision ID: 5823477b2b23
Revises: ecc85264d9a5
Create Date: 2026-09-03 17:59:03.270046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5823477b2b23'
down_revision: Union[str, None] = 'ecc85264d9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('movement_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('series_code', sa.String(length=20), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['movement_type_id'], ['movement_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'movement_type_id', 'year', name='uq_movement_series_company_type_year')
    )
    op.create_index(op.f('ix_movement_series_company_id'), 'movement_series', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_series_company_id'), table_name='movement_series')
    op.drop_table('movement_series')
    # ### end Alembic commands ###
