"""add unique constraint on denominations

Revision ID: 5e1d3a412227
Revises: 9039c3cc3f06
Create Date: 2026-09-09 09:53:27.202112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1d3a412227'
down_revision: Union[str, None] = '9039c3cc3f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.
    op.create_unique_constraint('uq_denomination_currency_value_type', 'denominations', ['currency_id', 'value', 'denomination_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_denomination_currency_value_type', 'denominations', type_='unique')
    # ### end Alembic commands ###
