"""Add StockMovementDocument and StockMovementDocumentLine

Revision ID: 6471a567b8c1
Revises: 5823477b2b23
Create Date: 2026-09-03 18:12:10.235331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6471a567b8c1'
down_revision: Union[str, None] = '5823477b2b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movement_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('movement_type_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('total_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['movement_type_id'], ['movement_types.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_documents_company_id'), 'stock_movement_documents', ['company_id'], unique=False)
    op.create_table('stock_movement_document_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_code_snapshot', sa.String(length=50), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['stock_movement_documents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movement_document_lines_document_id'), 'stock_movement_document_lines', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movement_document_lines_document_id'), table_name='stock_movement_document_lines')
    op.drop_table('stock_movement_document_lines')
    op.drop_index(op.f('ix_stock_movement_documents_company_id'), table_name='stock_movement_documents')
    op.drop_table('stock_movement_documents')
    # ### end Alembic commands ###
