"""Add print_count to Invoice

Revision ID: 71678f23a2f7
Revises: e32b9fe1862f
Create Date: 2026-09-03 01:05:59.106341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71678f23a2f7'
down_revision: Union[str, None] = 'e32b9fe1862f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('print_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'print_count')
    # ### end Alembic commands ###
