"""Add tax_category to VAT

Revision ID: 77d00db9e75c
Revises: 71678f23a2f7
Create Date: 2026-09-03 11:29:25.683671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d00db9e75c'
down_revision: Union[str, None] = '71678f23a2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vat_rates', sa.Column('tax_category', sa.String(length=10), nullable=False, server_default='NOR'))
    # Backfill existing rows by their percentage - see the standard 0/5/14 mapping used
    # throughout this project (Regime Geral/Exclusao seeding, VAT display, etc).
    op.execute("UPDATE vat_rates SET tax_category = 'ISE' WHERE rate = 0")
    op.execute("UPDATE vat_rates SET tax_category = 'RED' WHERE rate = 5")
    op.execute("UPDATE vat_rates SET tax_category = 'NOR' WHERE rate = 14")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vat_rates', 'tax_category')
    # ### end Alembic commands ###
