"""Add logo_path to companies

Revision ID: 8073642bd52e
Revises: c13ea55a153c
Create Date: 2026-08-21 13:56:07.208376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8073642bd52e'
down_revision: Union[str, None] = 'c13ea55a153c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_path')
    # ### end Alembic commands ###
