"""add unique constraint on user_cash_point_access.pos_id

Revision ID: 80c6e2230dc7
Revises: f3ec981688e8
Create Date: 2026-09-08 17:53:00.099426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c6e2230dc7'
down_revision: Union[str, None] = 'f3ec981688e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.
    op.create_unique_constraint('uq_user_cash_point_access_pos', 'user_cash_point_access', ['pos_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_cash_point_access_pos', 'user_cash_point_access', type_='unique')
    # ### end Alembic commands ###
