"""add generic booking system - resources and bookings

Revision ID: 83c885b9011d
Revises: debc6ed7cbd5
Create Date: 2026-09-13 01:05:57.492949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c885b9011d'
down_revision: Union[str, None] = 'debc6ed7cbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_activity_id'), 'resources', ['activity_id'], unique=False)
    op.create_index(op.f('ix_resources_company_id'), 'resources', ['company_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADA', 'EM_CURSO', 'CONCLUIDA', 'CANCELADA', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_company_id'), 'bookings', ['company_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_ends_at'), 'bookings', ['ends_at'], unique=False)
    op.create_index(op.f('ix_bookings_resource_id'), 'bookings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_bookings_starts_at'), 'bookings', ['starts_at'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_bookings_starts_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_resource_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_ends_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_company_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_resources_company_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_activity_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
