"""Split Product/Service, add ProductCategory, ServiceType

Revision ID: 8ee052c8239c
Revises: 1dc0c2365d66
Create Date: 2026-08-29 17:00:13.455268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee052c8239c'
down_revision: Union[str, None] = '1dc0c2365d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('not_available_purchases', sa.Boolean(), nullable=False),
    sa.Column('not_available_pos', sa.Boolean(), nullable=False),
    sa.Column('not_available_sales', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
    op.create_table('service_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('not_available_purchases', sa.Boolean(), nullable=False),
    sa.Column('not_available_pos', sa.Boolean(), nullable=False),
    sa.Column('not_available_sales', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_company_id'), 'service_types', ['company_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('unit_of_measure_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('withholding_tax_id', sa.UUID(), nullable=True),
    sa.Column('subject_to_return', sa.Boolean(), nullable=False),
    sa.Column('not_available_pos', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'SUSPENSO', 'BLOQUEADO', 'ESGOTADO', 'DESCONTINUADO', name='productservicestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure_catalog.id'], ),
    sa.ForeignKeyConstraint(['vat_id'], ['vat_rates.id'], ),
    sa.ForeignKeyConstraint(['withholding_tax_id'], ['withholding_taxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_service_company_code')
    )
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=False)
    op.create_index(op.f('ix_services_company_id'), 'services', ['company_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('unit_of_measure_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('unit_of_measure_legacy', sa.String(length=30), nullable=True))
    op.add_column('products', sa.Column('managed_by_batch', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('managed_by_stock', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('products', sa.Column('managed_by_expiry', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('not_available_pos', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('subject_to_return', sa.Boolean(), nullable=False, server_default='false'))
    op.execute("ALTER TABLE products ADD COLUMN status productservicestatus NOT NULL DEFAULT 'ACTIVO'")
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'unit_of_measure_catalog', ['unit_of_measure_id'], ['id'])
    op.execute("UPDATE products SET unit_of_measure_legacy = unit_of_measure")
    op.drop_column('products', 'unit_of_measure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_of_measure', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.execute("ALTER TABLE products DROP COLUMN status")
    op.drop_column('products', 'subject_to_return')
    op.drop_column('products', 'not_available_pos')
    op.drop_column('products', 'managed_by_expiry')
    op.drop_column('products', 'managed_by_stock')
    op.drop_column('products', 'managed_by_batch')
    op.drop_column('products', 'unit_of_measure_legacy')
    op.drop_column('products', 'unit_of_measure_id')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'image_path')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_services_company_id'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_service_types_company_id'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.execute("DROP TYPE productservicestatus")
    # ### end Alembic commands ###
