"""add denominations and cash_denomination_counts tables

Revision ID: 9039c3cc3f06
Revises: 80c6e2230dc7
Create Date: 2026-09-09 08:34:25.241025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9039c3cc3f06'
down_revision: Union[str, None] = '80c6e2230dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denominations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('denomination_type', sa.Enum('NOTA', 'MOEDA', name='denominationtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denominations_currency_id'), 'denominations', ['currency_id'], unique=False)
    op.create_table('cash_denomination_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cash_session_id', sa.UUID(), nullable=False),
    sa.Column('count_type', sa.Enum('ABERTURA', 'FECHO', 'TROCA_SAIDA', 'TROCA_ENTRADA', name='denominationcounttype'), nullable=False),
    sa.Column('counted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['counted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_denomination_counts_cash_session_id'), 'cash_denomination_counts', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_cash_denomination_counts_company_id'), 'cash_denomination_counts', ['company_id'], unique=False)
    op.create_table('cash_denomination_count_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('count_id', sa.UUID(), nullable=False),
    sa.Column('denomination_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['cash_denomination_counts.id'], ),
    sa.ForeignKeyConstraint(['denomination_id'], ['denominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_denomination_count_lines_count_id'), 'cash_denomination_count_lines', ['count_id'], unique=False)

    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here,
    # same as in prior migrations.
    # ### end Alembic commands ###

    # ### data: seed standard Kwanza (AOA) denominations, one row per note/coin ###
    connection = op.get_bind()
    aoa_currency = connection.execute(sa.text("SELECT id FROM currencies WHERE code = 'AOA'")).fetchone()
    if aoa_currency is not None:
        currency_id = aoa_currency[0]
        notes = [200, 500, 1000, 2000, 5000, 10000]
        coins = [1, 5, 10, 20, 50]
        for value in notes:
            connection.execute(
                sa.text(
                    "INSERT INTO denominations (id, currency_id, value, denomination_type, is_active, created_at) "
                    "VALUES (gen_random_uuid(), :currency_id, :value, 'NOTA', true, now())"
                ),
                {"currency_id": currency_id, "value": value},
            )
        for value in coins:
            connection.execute(
                sa.text(
                    "INSERT INTO denominations (id, currency_id, value, denomination_type, is_active, created_at) "
                    "VALUES (gen_random_uuid(), :currency_id, :value, 'MOEDA', true, now())"
                ),
                {"currency_id": currency_id, "value": value},
            )
    # If no AOA currency exists yet (e.g. fresh empty DB before any company is
    # created), denominations are simply left empty - SUPER_ADMIN can seed them
    # manually via the catalog screen once a currency exists.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_denomination_count_lines_count_id'), table_name='cash_denomination_count_lines')
    op.drop_table('cash_denomination_count_lines')
    op.drop_index(op.f('ix_cash_denomination_counts_company_id'), table_name='cash_denomination_counts')
    op.drop_index(op.f('ix_cash_denomination_counts_cash_session_id'), table_name='cash_denomination_counts')
    op.drop_table('cash_denomination_counts')
    op.drop_index(op.f('ix_denominations_currency_id'), table_name='denominations')
    op.drop_table('denominations')
    # ### end Alembic commands ###
