"""Add modules, company_modules, and Activity.module_id

Revision ID: 91dc41063b06
Revises: e874a95bba30
Create Date: 2026-08-25 10:20:56.677842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91dc41063b06'
down_revision: Union[str, None] = 'e874a95bba30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'module_id', name='uq_company_module')
    )
    op.create_index(op.f('ix_company_modules_company_id'), 'company_modules', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_modules_module_id'), 'company_modules', ['module_id'], unique=False)
    op.add_column('activities', sa.Column('module_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_activities_module_id'), 'activities', ['module_id'], unique=False)
    op.create_foreign_key(None, 'activities', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_activities_module_id'), table_name='activities')
    op.drop_column('activities', 'module_id')
    op.drop_index(op.f('ix_company_modules_module_id'), table_name='company_modules')
    op.drop_index(op.f('ix_company_modules_company_id'), table_name='company_modules')
    op.drop_table('company_modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
