"""Add vendor fields to platform_settings

Revision ID: 93e1f2d75f95
Revises: a571b2e70f67
Create Date: 2026-08-24 13:01:02.341159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e1f2d75f95'
down_revision: Union[str, None] = 'a571b2e70f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('vendor_tax_id', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('product_id', sa.String(length=100), nullable=True))
    op.add_column('platform_settings', sa.Column('product_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'product_version')
    op.drop_column('platform_settings', 'product_id')
    op.drop_column('platform_settings', 'vendor_tax_id')
    # ### end Alembic commands ###
