"""Add is_active to CompanyBankAccount

Revision ID: 96b141597813
Revises: bd01641a3df1
Create Date: 2026-08-29 08:09:59.020455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b141597813'
down_revision: Union[str, None] = 'bd01641a3df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_bank_accounts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_bank_accounts', 'is_active')
    # ### end Alembic commands ###
