"""add unique constraint on cash_movement_reasons

Revision ID: 97b8ac80d430
Revises: 5e1d3a412227
Create Date: 2026-09-09 22:24:02.110328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b8ac80d430'
down_revision: Union[str, None] = '5e1d3a412227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cash_movement_reason_company_name', 'cash_movement_reasons', ['company_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cash_movement_reason_company_name', 'cash_movement_reasons', type_='unique')
    # ### end Alembic commands ###
