"""Add commercial_registration_number to companies

Revision ID: a571b2e70f67
Revises: 528a358c62e1
Create Date: 2026-08-24 12:29:15.796336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a571b2e70f67'
down_revision: Union[str, None] = '528a358c62e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('commercial_registration_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'commercial_registration_number')
    # ### end Alembic commands ###
