"""Add is_fiscal to DocumentType

Revision ID: a57567888fac
Revises: deb899413b17
Create Date: 2026-09-02 15:06:11.972544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57567888fac'
down_revision: Union[str, None] = 'deb899413b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('is_fiscal', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'is_fiscal')
    # ### end Alembic commands ###
