"""Add unique constraints on company email and phone_number

Revision ID: a8eeff9db3ee
Revises: 50f26c210906
Create Date: 2026-08-20 23:11:46.640122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eeff9db3ee'
down_revision: Union[str, None] = '50f26c210906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_phone_number'), 'companies', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_phone_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    # ### end Alembic commands ###
