"""Enrich Company (3-tab fields) and add CompanyBankAccount

Revision ID: bd01641a3df1
Revises: 773b8bf14457
Create Date: 2026-08-29 07:42:06.749220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd01641a3df1'
down_revision: Union[str, None] = '773b8bf14457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE legalpersontype AS ENUM ('JURIDICA', 'FISICA')")
    op.execute("CREATE TYPE invoiceissuancemode AS ENUM ('MANUAL', 'ELETRONICA')")
    op.create_table('company_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_bank_accounts_company_id'), 'company_bank_accounts', ['company_id'], unique=False)
    op.add_column('companies', sa.Column('short_name', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('legal_person_type', sa.Enum('JURIDICA', 'FISICA', name='legalpersontype'), nullable=False, server_default='JURIDICA'))
    op.add_column('companies', sa.Column('phone_number_2', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('municipality_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('primary_currency_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('secondary_currency_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('uses_invoicing', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('companies', sa.Column('auto_series_year', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('companies', sa.Column('allows_future_sale_date', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('companies', sa.Column('suggests_last_document_date', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('companies', sa.Column('issuance_mode', sa.Enum('MANUAL', 'ELETRONICA', name='invoiceissuancemode'), nullable=False, server_default='MANUAL'))
    op.add_column('companies', sa.Column('electronic_signature_key', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'companies', 'currencies', ['secondary_currency_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'municipalities', ['municipality_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'currencies', ['primary_currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'electronic_signature_key')
    op.drop_column('companies', 'issuance_mode')
    op.drop_column('companies', 'suggests_last_document_date')
    op.drop_column('companies', 'allows_future_sale_date')
    op.drop_column('companies', 'auto_series_year')
    op.drop_column('companies', 'uses_invoicing')
    op.drop_column('companies', 'secondary_currency_id')
    op.drop_column('companies', 'primary_currency_id')
    op.drop_column('companies', 'municipality_id')
    op.drop_column('companies', 'province_id')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'phone_number_2')
    op.drop_column('companies', 'legal_person_type')
    op.drop_column('companies', 'short_name')
    op.drop_index(op.f('ix_company_bank_accounts_company_id'), table_name='company_bank_accounts')
    op.drop_table('company_bank_accounts')
    op.execute("DROP TYPE legalpersontype")
    op.execute("DROP TYPE invoiceissuancemode")
    # ### end Alembic commands ###
