"""Add address to companies

Revision ID: c13ea55a153c
Revises: 6e160bd852d6
Create Date: 2026-08-21 13:29:00.731231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13ea55a153c'
down_revision: Union[str, None] = '6e160bd852d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
