"""add internal consumption module - reasons catalog and records

Revision ID: c49f2476a4c3
Revises: 4cf1c781af9f
Create Date: 2026-09-16 09:30:39.921043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49f2476a4c3'
down_revision: Union[str, None] = '4cf1c781af9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_reason_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_consumption_reason_company_name')
    )
    op.create_index(op.f('ix_consumption_reason_catalog_company_id'), 'consumption_reason_catalog', ['company_id'], unique=False)
    op.create_table('internal_consumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('consumed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consumed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['consumption_reason_catalog.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_consumptions_activity_id'), 'internal_consumptions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_internal_consumptions_company_id'), 'internal_consumptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_internal_consumptions_product_id'), 'internal_consumptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_internal_consumptions_resource_id'), 'internal_consumptions', ['resource_id'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here.


def downgrade() -> None:
    op.drop_index(op.f('ix_internal_consumptions_resource_id'), table_name='internal_consumptions')
    op.drop_index(op.f('ix_internal_consumptions_product_id'), table_name='internal_consumptions')
    op.drop_index(op.f('ix_internal_consumptions_company_id'), table_name='internal_consumptions')
    op.drop_index(op.f('ix_internal_consumptions_activity_id'), table_name='internal_consumptions')
    op.drop_table('internal_consumptions')
    op.drop_index(op.f('ix_consumption_reason_catalog_company_id'), table_name='consumption_reason_catalog')
    op.drop_table('consumption_reason_catalog')
    # ### end Alembic commands ###
