"""Add Activity.warehouse_id

Revision ID: c4cd41d24cea
Revises: 91dc41063b06
Create Date: 2026-08-25 12:15:00.080245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cd41d24cea'
down_revision: Union[str, None] = '91dc41063b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('warehouse_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'activities', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'warehouse_id')
    # ### end Alembic commands ###
