"""Add area to DocumentType, issuance_mode to DocumentSeries

Revision ID: cbbc7d12504a
Revises: 4e5343cdb49b
Create Date: 2026-09-01 11:33:30.800849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbbc7d12504a'
down_revision: Union[str, None] = '4e5343cdb49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_series', sa.Column('issuance_mode', sa.String(length=20), nullable=True))
    op.execute("UPDATE document_series SET issuance_mode = CASE WHEN establishment_id IS NOT NULL OR contingency_indicator IS NOT NULL THEN 'ELETRONICA' ELSE 'MANUAL' END")
    op.alter_column('document_series', 'issuance_mode', nullable=False)
    op.execute("CREATE TYPE documenttypearea AS ENUM ('FACTURACAO', 'TESOURARIA', 'COMPRAS')")
    op.add_column('document_types', sa.Column('area', sa.Enum('FACTURACAO', 'TESOURARIA', 'COMPRAS', name='documenttypearea'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_types', 'area')
    op.execute("DROP TYPE documenttypearea")
    op.drop_column('document_series', 'issuance_mode')
    # ### end Alembic commands ###
