"""add user_cash_point_access table

Revision ID: d3a90de9c926
Revises: 05ccc3fa9605
Create Date: 2026-09-08 13:09:56.920936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a90de9c926'
down_revision: Union[str, None] = '05ccc3fa9605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cash_point_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pos_id', sa.UUID(), nullable=True),
    sa.Column('cash_office_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (pos_id IS NOT NULL AND cash_office_id IS NOT NULL)', name='ck_user_cash_point_access_single_target'),
    sa.CheckConstraint('pos_id IS NOT NULL OR cash_office_id IS NOT NULL', name='ck_user_cash_point_access_has_target'),
    sa.ForeignKeyConstraint(['cash_office_id'], ['cash_offices.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['points_of_sale.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_cash_point_access_user')
    )
    op.create_index(op.f('ix_user_cash_point_access_cash_office_id'), 'user_cash_point_access', ['cash_office_id'], unique=False)
    op.create_index(op.f('ix_user_cash_point_access_company_id'), 'user_cash_point_access', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_cash_point_access_pos_id'), 'user_cash_point_access', ['pos_id'], unique=False)
    op.create_index(op.f('ix_user_cash_point_access_user_id'), 'user_cash_point_access', ['user_id'], unique=False)
    # NOTE: 'uq_companies_name_lower' is a manually-created functional index (lower(name))
    # not represented in the SQLAlchemy Company model - intentionally NOT touched here,
    # same as in prior migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cash_point_access_user_id'), table_name='user_cash_point_access')
    op.drop_index(op.f('ix_user_cash_point_access_pos_id'), table_name='user_cash_point_access')
    op.drop_index(op.f('ix_user_cash_point_access_company_id'), table_name='user_cash_point_access')
    op.drop_index(op.f('ix_user_cash_point_access_cash_office_id'), table_name='user_cash_point_access')
    op.drop_table('user_cash_point_access')
    # ### end Alembic commands ###
