"""Add issuance_mode to Invoice

Revision ID: deb899413b17
Revises: 4f8e7fd5ac3e
Create Date: 2026-09-02 12:51:18.583839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb899413b17'
down_revision: Union[str, None] = '4f8e7fd5ac3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issuance_mode', sa.String(length=20), nullable=False, server_default='MANUAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'issuance_mode')
    # ### end Alembic commands ###
