"""Include issuance_mode in DocumentSeries unique constraint

Revision ID: e32b9fe1862f
Revises: 41d3d7c03137
Create Date: 2026-09-03 00:52:34.447761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32b9fe1862f'
down_revision: Union[str, None] = '41d3d7c03137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_series_company_doctype_year', 'document_series', type_='unique')
    op.create_unique_constraint('uq_series_company_doctype_year_mode', 'document_series', ['company_id', 'document_type_id', 'year', 'issuance_mode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_series_company_doctype_year_mode', 'document_series', type_='unique')
    op.create_unique_constraint('uq_series_company_doctype_year', 'document_series', ['company_id', 'document_type_id', 'year'])
    # ### end Alembic commands ###
