"""Enrich Invoice and InvoiceLine for full document flow

Revision ID: e405dd6833bf
Revises: 4bfbdf0bce8d
Create Date: 2026-09-01 14:32:33.949215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e405dd6833bf'
down_revision: Union[str, None] = '4bfbdf0bce8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.execute("CREATE TYPE documentlifecyclestatus AS ENUM ('EMITIDO', 'RECTIFICADO', 'RECTIFICADO_PARCIAL', 'ANULADO')")
    op.add_column('invoices', sa.Column('document_status', sa.Enum('EMITIDO', 'RECTIFICADO', 'RECTIFICADO_PARCIAL', 'ANULADO', name='documentlifecyclestatus'), nullable=False, server_default='EMITIDO'))
    op.add_column('invoices', sa.Column('reference_invoice_id', sa.UUID(), nullable=True))
    op.execute("CREATE TYPE creditnotereason AS ENUM ('ANL', 'RTF')")
    op.add_column('invoices', sa.Column('credit_note_reason', sa.Enum('ANL', 'RTF', name='creditnotereason'), nullable=True))
    op.add_column('invoices', sa.Column('credit_note_cause', sa.String(length=60), nullable=True))
    op.add_column('invoices', sa.Column('payment_term_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('payment_method_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('bank_account_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('observations', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('discount_global_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'invoices', 'payment_terms', ['payment_term_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'payment_method_catalog', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'invoices', ['reference_invoice_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'company_bank_accounts', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'discount_global_percent')
    op.drop_column('invoices', 'observations')
    op.drop_column('invoices', 'payment_date')
    op.drop_column('invoices', 'amount_received')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'bank_account_id')
    op.drop_column('invoices', 'payment_method_id')
    op.drop_column('invoices', 'payment_term_id')
    op.drop_column('invoices', 'credit_note_cause')
    op.drop_column('invoices', 'credit_note_reason')
    op.drop_column('invoices', 'reference_invoice_id')
    op.drop_column('invoices', 'document_status')
    op.execute("DROP TYPE documentlifecyclestatus")
    op.execute("DROP TYPE creditnotereason")
    op.drop_column('invoice_lines', 'discount_percent')
    # ### end Alembic commands ###
