"""Add number_digits to activities and invoices

Revision ID: e874a95bba30
Revises: 734da398aa02
Create Date: 2026-08-25 09:49:30.009519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e874a95bba30'
down_revision: Union[str, None] = '734da398aa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('number_digits', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('number_digits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'number_digits')
    op.drop_column('activities', 'number_digits')
    # ### end Alembic commands ###
