"""Add code, address, and toggle fields to Warehouse

Revision ID: e8f69cea69d6
Revises: 6471a567b8c1
Create Date: 2026-09-04 20:05:18.830217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f69cea69d6'
down_revision: Union[str, None] = '6471a567b8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('code', sa.String(length=20), nullable=True))
    op.add_column('warehouses', sa.Column('province_id', sa.UUID(), nullable=True))
    op.add_column('warehouses', sa.Column('municipality_id', sa.UUID(), nullable=True))
    op.add_column('warehouses', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('warehouses', sa.Column('allow_negative_stock', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('warehouses', sa.Column('entradas_bloqueadas', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('warehouses', sa.Column('saidas_bloqueadas', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('warehouses', sa.Column('gerido_por_familia_tipo', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_foreign_key(None, 'warehouses', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'warehouses', 'municipalities', ['municipality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'gerido_por_familia_tipo')
    op.drop_column('warehouses', 'saidas_bloqueadas')
    op.drop_column('warehouses', 'entradas_bloqueadas')
    op.drop_column('warehouses', 'allow_negative_stock')
    op.drop_column('warehouses', 'address')
    op.drop_column('warehouses', 'municipality_id')
    op.drop_column('warehouses', 'province_id')
    op.drop_column('warehouses', 'code')
    # ### end Alembic commands ###
