"""Add MovementType catalog

Revision ID: ecc85264d9a5
Revises: 77d00db9e75c
Create Date: 2026-09-03 17:27:00.089043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc85264d9a5'
down_revision: Union[str, None] = '77d00db9e75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('ENTRADA', 'SAIDA', name='movementdirection'), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_types')
    # ### end Alembic commands ###
