"""Add counterpart_warehouse_id and is_transfer_source to StockMovement

Revision ID: ef64a2ad8c64
Revises: 656364042b58
Create Date: 2026-08-25 14:47:59.457802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef64a2ad8c64'
down_revision: Union[str, None] = '656364042b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('counterpart_warehouse_id', sa.UUID(), nullable=True))
    op.add_column('stock_movements', sa.Column('is_transfer_source', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'warehouses', ['counterpart_warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'is_transfer_source')
    op.drop_column('stock_movements', 'counterpart_warehouse_id')
    # ### end Alembic commands ###
