"""Make company_id nullable on users, add SUPER_ADMIN role

Revision ID: f8f53b52fd1e
Revises: 055ec2b7b702
Create Date: 2026-08-20 16:51:44.817592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f53b52fd1e'
down_revision: Union[str, None] = '055ec2b7b702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'SUPER_ADMIN'")
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

